### ISSUE TITLE
Get Everything to Work in CMSSW 104X

### ISSUE THREAD

**Issue by JHiltbrand** [UMN-CMS/cmsWRextensions#6]
Currently, working in with specific release CMSSW_10_4_0_patch1. The working branch is `tweaksFor104X`

**TODO LIST**

- [x]  Jet resolution text file on L169 of cmsWRextension.cc is hard coded to a 2016 file. This needs to be flexible for all three years of Run II.

- [x]  Choosing globaltag and JSON file in job submission script should figure out which tags / JSON to use based on the year being run over.

- [x] Jet correction uncertainty values text file needs to not be hard coded for 2016.

- [ ] Figure out muon efficiencies/SFs and PU weights for all three years.

**Comment by JHiltbrand** [comment]
Minor changes to allow compilation:

In TunePMuonProducer.cc:

- `std::auto_ptr` needed to be changed to a `std::unique_ptr` with `event.put(mus)` becoming `event.put(std::move(mus))`. **NOTE:** `std::unique_ptr` is compatible with CMSSW_8_1_X and up. 

In cmsWRextension.h:

- `#include "FWCore/Framework/interface/EDAnalyzer.h"`
